---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
    name: __service_name__
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ template "fullname" . }}
    template:
      metadata:
        labels:
          provider: fabric8
          app: {{ template "fullname" . }}
          chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
          version: 1.0.0
      spec:
        containers:
        - image: "{{ .Values.__service_name__.image.name }}:{{ .Values.__service_name__.image.tag }}"
          imagePullPolicy: {{ .Values.__service_name__.image.pullPolicy }}
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 80
          name: __service_name__
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          securityContext:
            privileged: false
