kubernetes:
  host: https://kubernetes.default

helloworld:
  namespace: __stackname__
  image:
    name: __registryhost__/__image_name__
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress
